### PR TITLE
Integrate app theme

### LINKED ISSUE #5: Integrate the theme
integrate the theme base on the figma project:
https://www.figma.com/design/pHzaH12CC0gt4X3sLvJEOw/SABITOU?node-id=387-8287&node-type=frame&t=AXTctMRrrpR9iPUv-0

Reference:
- https://m3.material.io/blog/material-theme-builder
- https://material-foundation.github.io/material-theme-builder/
- https://flutter-shadcn-ui.mariuti.com (this package provide a great way to design the theme a also have the great reusable component)

fill free to choose what you want or make some proposal.

### PR DESCRIPTION
**Pull request by Kurocifer**
Fixes #5 

Changes proposed in this pull request:
- Add a basic version of the app theme
- Add the different colors used by app in the constants.dart file

### CODE REVIEW

**Comment by Kurocifer** [comment]
@warrenrhodes I don't know how good this is. I don't know if this was expected to be done for the setting up of the theme

**Comment by warrenrhodes** [comment]
> Fixes #5
> 
> Changes proposed in this pull request:
> 
> * Add a basic version of the app theme
> * Add the different colors used by app in the constants.dart file

This implementation will normally work but the code isn't organise.
as expected we have the `themes` directory who normally going to contains all the files and data  to manage the theme.
here is my expectation exemple:
```dart
>> theme/colors_schema.dart
final class AppColors {
  static const Color transparent = Colors.transparent;
  static const Color success900 = Color(0x084D2D);
  static const Color success100 = Color(0xB6E9D1);
}
>> theme/text_styles.dart

/// List of Customers font weights.
final class AppFontWeights {
  /// The bold font weight.
  static const semiBold = FontWeight.w600;
}
final class AppFontSizes {
 static const sm = 14;
  static const md = 16;
  static const lg = 18
  static const xl = 20
  static const 2xl = 24
  static const 3xl = 30
  static const 4xl = 36
}

>> themes/app_theme.dart

final class Themes {
const ThemeData darkTheme() => FlexThemeData.dark(...);
const ThemeData lightTheme() => FlexThemeData.light(...);
} 
```

**Comment by Kurocifer** [comment]
Now I see. it's true it's a clearer and better implementation let me update my code then.

**Comment by Kurocifer** [comment]
Updated it and moved them to the themes folder as it should have been. Please will like to know what it needs more or this is okay

**Pull request closed without merging**
